import type { GeneratedAlias, GeneratedIcon, GeneratedRemoval, IconSet } from './collectIcons.ts';
import { escapeSwiftIdentifier } from './swiftIdentifier.ts';

export interface GenerationContext {
  /** The `lucide-static` version the font was taken from. */
  lucideVersion: string;
  /** The Swift module the package exposes, `LucideIcons` by default. */
  moduleName: string;
  familyName: string;
  postScriptName: string;
  fontFileName: string;
}

function header(context: GenerationContext, description: string): string {
  return [
    '//',
    '// This file is generated by `pnpm build:swift`, do not edit it by hand.',
    '//',
    `// ${description}`,
    `// Source: lucide-static@${context.lucideVersion}`,
    '//',
    '',
  ].join('\n');
}

function hex(codePoint: number): string {
  return `0x${codePoint.toString(16).toUpperCase().padStart(4, '0')}`;
}

function docComment(icon: GeneratedIcon): string {
  const lines = [`    /// The \`${icon.name}\` icon.`];

  if (icon.aliasNames.length > 0) {
    const aliasList = icon.aliasNames.map((alias) => `\`${alias}\``).join(', ');
    lines.push('    ///', `    /// Also known as ${aliasList}.`);
  }

  return lines.join('\n');
}

function declaration(identifier: string, name: string, codePoint: number): string {
  return `    public static let ${escapeSwiftIdentifier(identifier)} = LucideIcon("${name}", codePoint: ${hex(codePoint)})`;
}

export function generateIconsFile(iconSet: IconSet, context: GenerationContext): string {
  const body = iconSet.icons
    .map((icon) => {
      const lines = [docComment(icon)];

      if (icon.deprecated) {
        lines.push(
          `    @available(*, deprecated, message: "'${icon.name}' is deprecated in Lucide.")`,
        );
      }

      lines.push(declaration(icon.identifier, icon.name, icon.codePoint));

      return lines.join('\n');
    })
    .join('\n\n');

  return [
    header(context, `${iconSet.icons.length} icons of the bundled Lucide icon font.`),
    'extension LucideIcon {',
    body,
    '}',
    '',
  ].join('\n');
}

export function generateAliasesFile(iconSet: IconSet, context: GenerationContext): string {
  const body = iconSet.aliases
    .map((alias: GeneratedAlias) => {
      const lines = [
        `    /// \`${alias.name}\`, an alias of the \`${alias.iconName}\` icon.`,
        '    ///',
        `    /// Resolves to \`LucideIcon.${alias.iconIdentifier}\`.`,
      ];

      if (alias.deprecated) {
        lines.push(
          `    @available(*, deprecated, renamed: "LucideIcon.${alias.iconIdentifier}", message: "'${alias.name}' is a deprecated alias of '${alias.iconName}'.")`,
        );
      }

      // Aliases resolve to their canonical icon, so `LucideIcon.alarmCheck`
      // equals `LucideIcon.alarmClockCheck` and persists as the canonical name.
      lines.push(declaration(alias.identifier, alias.iconName, alias.codePoint));

      return lines.join('\n');
    })
    .join('\n\n');

  return [
    header(
      context,
      `${iconSet.aliases.length} alternative names, each resolving to its canonical icon.`,
    ),
    'extension LucideIcon {',
    body,
    '}',
    '',
  ].join('\n');
}

export function generateRemovedFile(iconSet: IconSet, context: GenerationContext): string {
  const body = iconSet.removed
    .map((removal: GeneratedRemoval) => {
      return [
        `    /// \`${removal.name}\`, an icon that was removed from Lucide.`,
        '    ///',
        '    /// The name keeps its code point so old data stays readable, but the font',
        '    /// has no glyph for it any more: it renders as blank space.',
        `    @available(*, deprecated, message: "'${removal.name}' was removed from Lucide and has no glyph in the bundled font, pick a different icon.")`,
        declaration(removal.identifier, removal.name, removal.codePoint),
      ].join('\n');
    })
    .join('\n\n');

  return [
    header(
      context,
      `${iconSet.removed.length} names that were removed from Lucide and no longer have a glyph.`,
    ),
    'extension LucideIcon {',
    body,
    '}',
    '',
  ].join('\n');
}

export function generateMetadataFile(iconSet: IconSet, context: GenerationContext): string {
  return [
    header(context, 'Metadata about the bundled font.'),
    'extension LucideFont {',
    '    /// The `lucide-static` release the bundled font was generated from.',
    `    public static let lucideVersion = "${context.lucideVersion}"`,
    '',
    '    /// The font family name, as registered with Core Text.',
    `    public static let familyName = "${context.familyName}"`,
    '',
    '    /// The PostScript name to pass to `UIFont(name:size:)` or `Font.custom(_:size:)`.',
    `    public static let postScriptName = "${context.postScriptName}"`,
    '',
    '    /// The name of the font file inside the package bundle.',
    `    public static let fontFileName = "${context.fontFileName}"`,
    '',
    '    /// The number of icons in the bundled font.',
    `    public static let iconCount = ${iconSet.icons.length}`,
    '',
    '    /// The number of alternative icon names in the bundled font.',
    `    public static let aliasCount = ${iconSet.aliases.length}`,
    '}',
    '',
  ].join('\n');
}

export function generateIndexJson(iconSet: IconSet, context: GenerationContext): string {
  const icons: Record<string, number> = {};
  const aliases: Record<string, string> = {};
  const removed: Record<string, number> = {};

  for (const icon of iconSet.icons) {
    icons[icon.name] = icon.codePoint;
  }

  for (const alias of iconSet.aliases) {
    aliases[alias.name] = alias.iconName;
  }

  for (const removal of iconSet.removed) {
    removed[removal.name] = removal.codePoint;
  }

  return `${JSON.stringify(
    {
      lucideVersion: context.lucideVersion,
      fontFamilyName: context.familyName,
      fontPostScriptName: context.postScriptName,
      icons,
      aliases,
      removed,
    },
    null,
    2,
  )}\n`;
}

/**
 * A list of every generated constant, used by the package's tests to check the
 * constants against the font and the index. It lives in the test target so the
 * library itself doesn't carry an array of every icon.
 */
export function generateTestConstantsFile(iconSet: IconSet, context: GenerationContext): string {
  const chunkSize = 250;
  const chunks: GeneratedIcon[][] = [];

  for (let index = 0; index < iconSet.icons.length; index += chunkSize) {
    chunks.push(iconSet.icons.slice(index, index + chunkSize));
  }

  // Split into chunks, a single array literal of a few thousand elements makes
  // the Swift type checker crawl.
  const chunkDeclarations = chunks.map((chunk, index) =>
    [
      `private let iconConstants${index}: [(name: String, icon: LucideIcon)] = [`,
      ...chunk.map((icon) => `    ("${icon.name}", .${escapeSwiftIdentifier(icon.identifier)}),`),
      ']',
    ].join('\n'),
  );

  const chunkSum =
    chunks.length > 0 ? chunks.map((_, index) => `iconConstants${index}`).join(' + ') : '[]';

  return [
    header(context, 'Every generated icon constant, for the parity tests.'),
    `import ${context.moduleName}`,
    '',
    ...chunkDeclarations,
    '',
    '/// Every icon constant the generator emitted, paired with the name it was',
    '/// generated for.',
    `let generatedIconConstants: [(name: String, icon: LucideIcon)] = ${chunkSum}`,
    '',
    '/// Every alias name and the canonical icon name it resolves to.',
    'let generatedAliasNames: [(alias: String, iconName: String)] = [',
    ...iconSet.aliases.map((alias) => `    ("${alias.name}", "${alias.iconName}"),`),
    ']',
    '',
    '/// Every name that kept its code point but lost its glyph.',
    'let generatedRemovedNames: [String] = [',
    ...iconSet.removed.map((removal) => `    "${removal.name}",`),
    ']',
    '',
  ].join('\n');
}
